# Generated by Django 5.2.4 on 2025-07-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
