# Generated by Django 5.2.4 on 2025-07-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0002_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="get_full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.FileField(blank=True, upload_to="profile_pic/"),
        ),
    ]
